version: "3.8"

services:
  mysql:
    container_name: mysql
    platform: linux/x86_64
    build: ./mysql/
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/db:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
    env_file:
      - ./mysql/local.env
    tty: true
    environment:
      - MYSQL_ROOT_PASSWORD=P4ssw0rd
      - MYSQL_USER=appuser
      - MYSQL_PASSWORD=P4ssw0rd
      - MYSQL_DATABASE=cricket_data
    command: --default-authentication-plugin=mysql_native_password

  api:
    container_name: fast_api
    platform: linux/x86_64
    build:
      context: ./api
      dockerfile: dev.Dockerfile
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - ./api/local.env
    depends_on:
      - mysql
    volumes:
      - ./api:/app
    tty: true
  client:
    build:
      context: ./client
    # This will force server service to build and start before client.
    depends_on:
      - api
      - mysql
    ports:
      - 3000:3000
    environment:
      CHOKIDAR_USEPOLLING: "true"

volumes:
  mysql_data:
